'use strict';
let render = require('gulp-nunjucks-render');
let data   = require('gulp-data');

module.exports = (config) => (glyphs) => {
	util.log(util.colors.blue('Generating ' + config.sassDest + '/' + config.sassOutputName));
	render.nunjucks.configure(config.nunjucks, { watch: false });

	return gulp.src(config.template)
		.pipe(plumber(handleErrors))
		.pipe(data({
			icons: glyphs.map((glyph) => {
				util.log(util.colors.green('+ adding ' + glyph.name + ' glyph'));
				return {
					name: glyph.name,
					code: glyph.unicode[0].charCodeAt(0).toString(16).toUpperCase()
				};
			}),
			fontName: config.options.fontName,
			fontPath: config.fontPath,
			className: config.className,
			comment: '// DO NOT EDIT DIRECTLY!\n// Generated by gulpfile.js/tasks/iconFont.js from ' + config.template
		}))
		.pipe(render({
			path: config.template
		}))
		.pipe(rename(config.sassOutputName))
		.pipe(gulp.dest(config.sassDest));
};
